### PR TITLE
Scala 2.13.6, Scala 3.0.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@rossabaker WDYT?

**Comment by rossabaker** [comment]
Sorry, this must have gotten caught in a Notification Bankruptcy.

It looks right, but we've lost CI. It would be wonderful if someone could tackle #59 so we can test this on something other than a laptop.

**Comment by rossabaker** [comment]
The 2.13.6 is superseded by #83.  Getting on 3.0.2 would be good.

**Comment by rossabaker** [comment]
Included in #86

**Pull request closed without merging**
