### PR TITLE
add Scala 3.0.0-M3

### PR DESCRIPTION
**Pull request by sullis**
https://dotty.epfl.ch/blog/2020/12/18/scala3-m3.html

This PR adds Scala 3.0.0-M3 and drops Scala 3.0.0-M1

### CODE REVIEW

**Comment by rossabaker** [comment]
If this hits problems in CI, I wouldn't mind dropping 3.0.0-M1.  The rough guideline on a lot of projects has been to try to support the previous two.

Would be nice to get #64 cleaned up and do another milestone, but I'd prioritize this over that if we're all busy.

**Comment by rossabaker** [comment]
Looks like there's no scalacheck for all three Dotty milestones.  I think that's justification for dropping -M1.

**Comment by sullis** [comment]
> Looks like there's no scalacheck for all three Dotty milestones. I think that's justification for dropping -M1.


I just removed 3.0.0-M1

**Comment by sullis** [comment]
```
 sbt ++3.0.0-M3 compile  
```

Compile error:

```
[info] compiling 7 Scala sources to /Users/foobar/code/log4s/core/jvm/target/scala-3.0.0-M3/classes ...
[error] -- [E008] Not Found Error: /Users/foobar/code/log4s/core/shared/src/main/scala-3.0.0-M3/org/log4s/LoggerMacros.scala:35:29 
[error] 35 |          if (flags.is(Flags.ModuleClass & Flags.Object)) {
[error]    |                       ^^^^^^^^^^^^^^^^^
[error]    |           value ModuleClass is not a member of qctx.reflect.FlagsModule
[error] one error found
[error] one error found
[error] (coreJVM / Compile / compileIncremental) Compilation failed
```

**Comment by rossabaker** [comment]
The usage of it in that diff changed to `Flags.Module`.  Do the tests still pass if you make the corresponding change here?

**Comment by sullis** [comment]
> The usage of it in that diff changed to `Flags.Module`. Do the tests still pass if you make the corresponding change here?

I just fixed the compile error. Here's what I changed: 
https://github.com/Log4s/log4s/pull/67/commits/6c214c2ace9bb3b3ede3ac3737033535bf28465c

**Comment by sullis** [comment]
the CI build passed 👍

**Review by rossabaker — APPROVED** [review]
:+1:

**Pull request merged**
