### PR TITLE
Release notes for 1.10.0

### PR DESCRIPTION
**Pull request by rossabaker**
Mostly to ping @sarahgerweck since this will be a production release instead of the milestone releases I've been doing without her.  The scala.js support for Scala 3 is just a few minutes old, but we've always classified that as experimental anyway.  Releasing this will unblock prod releases of some other projects (e.g., http4s).

### CODE REVIEW

**Comment by rossabaker** [comment]
Going to do a release candidate, just so people can try it.

**Comment by sarahgerweck** [comment]
Hey @rossabaker 👍🏻. Thanks for getting this there. I would call it a proper release and just tag the ScalaJS as experimental and release note any issues. If there are issues, I don't think they'll be Log4s's issues—and I don't think there's any great harm if we have to do a patch to make improvements.

**Comment by aeons** [comment]
It doesn't look like the RC1 was published. Is Travis even still working for open source stuff?

**Comment by rossabaker** [comment]
Releases are manual via sbt-release, which I did.  What I failed to do was release from Sonatype staging. :grimacing:  Fixing that, and I'll do the final release later.

**Pull request merged**
