### PR TITLE
Build for 2.12.0-M5

### PR DESCRIPTION
**Pull request by larsrh**
`+ test` works (at least on my machine)

### CODE REVIEW

**Comment by larsrh** [comment]
Even though there's a `.travis.yml` in the root, Travis doesn't seem to pick up the build. Not sure what's wrong.

**Comment by colindean** [comment]
RC1 is out now..

**Comment by larsrh** [comment]
I can update the PR in case @sarahgerweck is interested. But there's still the problem that Travis won't build the branch, which ideally I'd like to see enabled before pushing.

**Comment by larsrh** [comment]
I took the liberty of releasing a [fork](https://github.com/larsrh/log4s): `"info.hupel.fork.org.log4s" %% "log4s" % "2.0"`. I'd be more than happy to contribute the changes back upstream in case anyone is interested.

**Pull request closed without merging**
