### PR TITLE
Switch to blackbox.Context

### PR DESCRIPTION
**Pull request by rossabaker**
`LogCtx` works fine as a blackbox macro.

### CODE REVIEW

**Comment by sarahgerweck** [comment]
Do you have a use case where this is preferable on these older Scala versions?

Although it will technically work as a blackbox macro, the bytecode you get is not as well optimized in this case. Here's a comparison snippet from a decompilation `log4s/core/jvm/target/scala-2.11/test-classes/org/log4s/LoggerSpec.class`

```java
// With Whitebox
if (this.$outer.org$log4s$LoggerSpec$$testLogger.isInfoEnabled()) {
    this.$outer.org$log4s$LoggerSpec$$testLogger.info(new scala.StringContext((Seq)scala.Predef$.MODULE$.wrapRefArray((Object[])new String[]{"info", ""})).s((Seq)scala.Predef$.MODULE$.genericWrapArray((Object)new Object[]{BoxesRunTime.boxToInteger((int)2)})));
}

// With Blackbox
if (this.$outer.org$log4s$LoggerSpec$$testLogger.isInfoEnabled()) {
    this.$outer.org$log4s$LoggerSpec$$testLogger.info(new scala.StringContext((Seq)scala.Predef$.MODULE$.wrapRefArray((Object[])new String[]{"info", ""})).s((Seq)scala.Predef$.MODULE$.genericWrapArray((Object)new Object[]{BoxesRunTime.boxToInteger((int)2)})));
    boxedUnit2 = scala.runtime.BoxedUnit.UNIT;
} else {
    boxedUnit2 = scala.runtime.BoxedUnit.UNIT;
}
```

I'm open to something like a split build if there's a use case, but I'm hesitant to deoptimize the bytecode just to make the maintenance slightly easier. (At some point I'll drop support for Scala 2.10 & 2.11, and this won't be an issue at all.)

**Comment by rossabaker** [comment]
I was thinking in terms of minimal power and futureproofing.  I didn't realize that there was such a bytecode difference.  I agree with you.  Closing.

**Comment by sarahgerweck** [comment]
Yeah, it's arguably a bug in the blackbox macro system. My observation is that it seems to insist on writing the result of each macro expansion into a variable even if it's never used, so it has to create the `else` clause and lookup the `UNIT` singleton even though it's pretty useless.

If it affected 2.12 it might be worth fixing the macro generator, but really I don't think many people are using Scala 2.10 or 2.11 at this point. (After 2.13 goes gold, I'll probably drop 2.10 & 2.11 support the first time they require any special development effort unless somebody wants to argue for their continued support. It's maybe also time to start thinking about the future of Log4s under Scala 3.0. I'm not sure how it fits into the new Tasty/Scalameta world.)

**Comment by rossabaker** [comment]
I don't know anything more than [this year-old post](https://www.scala-lang.org/blog/2018/04/30/in-a-nutshell.html#future-macros), but the fact that log4s _can_ be expressed without whitebox macros leaves me hopeful for log4s' future.

I'm on Scala 2.11 until I retire some devops debt, but I think your support plan sounds great.  Most major libraries dropped 2.10 long ago, the 2.11 compiler isn't maintained anymore, etc.

**Pull request closed without merging**
