### PR TITLE
Bump up SBT to 1.4.2

### PR DESCRIPTION
**Pull request by satorg**
...just to keep it up-to-date.

Not sure if it really matters, but can come in handy.

### CODE REVIEW

**Comment by satorg** [comment]
There are also a bunch of outdated dependencies:
```
Found 1 dependency update for log4s-testing
  org.slf4j:slf4j-api : 1.7.25 -> 1.7.30
Found 2 dependency updates for log4s-testing
  org.scala-js:scalajs-compiler:plugin->default(compile) : 1.0.1            -> 1.3.0
  org.slf4j:slf4j-api                                    : 1.7.25 -> 1.7.30         
Found 4 dependency updates for log4s
  org.scala-js:scalajs-compiler:plugin->default(compile) : 1.0.1              -> 1.3.0  
  org.scalatest:scalatest:test                           : 3.1.1   -> 3.1.4   -> 3.2.2  
  org.scalatestplus:scalacheck-1-14:test                 : 3.1.1.1 -> 3.1.4.0 -> 3.2.2.0
  org.slf4j:slf4j-api                                    : 1.7.25  -> 1.7.30            
Found 3 dependency updates for log4s
  org.scalatest:scalatest:test           : 3.1.1   -> 3.1.4   -> 3.2.2  
  org.scalatestplus:scalacheck-1-14:test : 3.1.1.1 -> 3.1.4.0 -> 3.2.2.0
  org.slf4j:slf4j-api                    : 1.7.25  -> 1.7.30            
```
Does it make sense to refresh some or all of them as well?

In particular, ScalaJS looks quite outdated (1.0.1 vs 1.3.0).

**Comment by rossabaker** [comment]
All of those look good to me, but I don't follow scala.js development. My understanding is that they do semver, so it should be fine.

We should also consider adopting Scala Steward.

**Review by rossabaker — APPROVED** [review]
Many of those mentioned just got merged, and Scala Steward will soon be finding the rest.

**Comment by jeffrey-aguilera** [comment]
There are some memory leaks that ultimately result in OOM when using 1.4.1 client. Recommend 1.4.2

**Pull request merged**
