### PR TITLE
update sbt plugins

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by sarahgerweck** [comment]
@xuwei-k is there any particular motivation for this PR?

**Comment by sarahgerweck** [comment]
Based on your blog, I believe this PR, which requires me to do all the testing, is an attempt to game GitHub statistics so you appear to be a contributor to projects where you didn't contribute anything material. If you can convince me otherwise, I'll happily accept your changes, otherwise please don't submit any more PRs like this.

**Comment by eed3si9n** [comment]
> Based on your blog, I believe this PR, which requires me to do all the testing since it changes publish-to-Sonatype plugins, is an attempt to game GitHub statistics so you appear to be a contributor to projects where you didn't contribute anything material.

It's ultimately up to project maintainers to accept or reject contributions because it doesn't come with tests or disagreements etc, but I think this is an unfair characterization of Yoshida-san's PR.

MiMa bump normally doesn't require additional work, but it often is finding corner cases of binary incompatibility. In this case 0.2.0 should bring the fix for https://github.com/lightbend/migration-manager/issues/196. sbt-pgp 1.1.1 brings in https://github.com/sbt/sbt-pgp/pull/121.

Also it's fairly common for contributors to first made superficial changes before they get into more meatier stuff. He does a lot for the community, so I had to say something.

**Comment by sarahgerweck** [comment]
Thanks @eed3si9n: I appreciate the data point. As I said in my previous comment, I have no intention to discourage people from helping, but this no-description PR felt weird, and seemed to be part of a pattern. If I'm wrong, then @xuwei-k like I said initially please feel free to make contributions.

**Pull request closed without merging**
