### PR TITLE
Scala 2.13.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks like this breaks the site generation on 2.13.1 somehow.

**Comment by sarahgerweck** [comment]
It actually doesn’t compile:
```
[error] /home/travis/build/Log4s/log4s/core/js/src/main/scala/org/log4s/log4sjs/Log4s.scala:13:16: reference to Log4sConfig is ambiguous;
[error] it is both defined in trait package-platform and available as object Log4sConfig in package log4sjs
[error]   val Config = Log4sConfig
```
This might be easy to fix, but it should retain binary compatibility. I won’t have time to look at it right away unless it‘s affecting 2.13.1 _users_ (which seems unlikely).

**Comment by rossabaker** [comment]
Yes, my mistake. I looked too hastily and didn't notice `test makeSite` were the same step.

We might consider adding to Scala Steward, which would:
1. Automate PRs like this if they work, including alerting us to problems when we break.
2. Keep plugins like sbt-mima current so we have the latest tools to verify compatibility of the fix.

**Comment by sullis** [comment]
obsolete.

**Comment by sullis** [comment]
superseded by https://github.com/Log4s/log4s/pull/50

**Pull request closed without merging**
